const GET_COMPANY_CODE_SUCCESS = "GET_COMPANY_CODE_SUCCESS";
const GET_COMPANY_CODE_FAILURE = "GET_COMPANY_CODE_FAILURE";
const GET_AFFILIATE_DATA_SUCCESS = "GET_AFFILIATE_DATA_SUCCESS";
const GET_AFFILIATE_DATA_FAILURE = "GET_AFFILIATE_DATA_FAILURE";
const GET_ALL_FY_YEAR_SUCCESS = "GET_ALL_FY_YEAR_SUCCESS";
const GET_ALL_FY_YEAR_FAILURE = "GET_ALL_FY_YEAR_FAILURE";

module.exports = {
  GET_COMPANY_CODE_SUCCESS,
  GET_COMPANY_CODE_FAILURE,
  GET_AFFILIATE_DATA_SUCCESS,
  GET_AFFILIATE_DATA_FAILURE,
  GET_ALL_FY_YEAR_SUCCESS,
  GET_ALL_FY_YEAR_FAILURE,
};
